apiVersion: v1
kind: Service
metadata:
  name: {{ include "grpc-demo.fullname" . }}
  labels:
{{ include "grpc-demo.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
      name: grpc
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "grpc-demo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
