apiVersion: v1
kind: Service
metadata:
  name: {{ include "suika-db.fullname" . }}
  labels:
{{ include "suika-db.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: {{ include "suika-db.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
