// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ping-pong.proto

package demo

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ping struct {
	Ping                 string   `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_62311b0d1f5d3673, []int{0}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetPing() string {
	if m != nil {
		return m.Ping
	}
	return ""
}

type Pong struct {
	Pong                 string   `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_62311b0d1f5d3673, []int{1}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetPong() string {
	if m != nil {
		return m.Pong
	}
	return ""
}

func init() {
	proto.RegisterType((*Ping)(nil), "demo.Ping")
	proto.RegisterType((*Pong)(nil), "demo.Pong")
}

func init() { proto.RegisterFile("ping-pong.proto", fileDescriptor_62311b0d1f5d3673) }

var fileDescriptor_62311b0d1f5d3673 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0xc8, 0xcc, 0x4b,
	0xd7, 0x2d, 0xc8, 0xcf, 0x4b, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0x49, 0xcd,
	0xcd, 0x97, 0x92, 0x49, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f, 0xcc,
	0xcb, 0xcb, 0x2f, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0x86, 0xa8, 0x51, 0x92, 0xe2, 0x62, 0x09,
	0xc8, 0xcc, 0x4b, 0x17, 0x12, 0xe2, 0x62, 0x01, 0x69, 0x97, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c,
	0x02, 0xb3, 0xc1, 0x72, 0xf9, 0x50, 0xb9, 0x7c, 0x24, 0xb9, 0xfc, 0xbc, 0x74, 0xa3, 0xc9, 0x8c,
	0x5c, 0x1c, 0x20, 0x8d, 0x60, 0x05, 0x8e, 0x5c, 0x6c, 0xc1, 0x25, 0x45, 0xa9, 0x89, 0xb9, 0x42,
	0x5c, 0x7a, 0x20, 0x3b, 0xf5, 0x40, 0x32, 0x52, 0x30, 0x76, 0x7e, 0x5e, 0xba, 0x92, 0x74, 0xd3,
	0xe5, 0x27, 0x93, 0x99, 0x44, 0x95, 0x04, 0xf4, 0x41, 0x26, 0x83, 0x4c, 0xd0, 0x2f, 0x06, 0xeb,
	0xb0, 0x62, 0xd4, 0xd2, 0x60, 0x34, 0x60, 0x14, 0x72, 0xe1, 0x62, 0x77, 0x4a, 0x4c, 0xce, 0x4e,
	0xcd, 0x4b, 0xc1, 0x69, 0x86, 0x22, 0xd8, 0x0c, 0x69, 0x21, 0x49, 0x84, 0x19, 0x49, 0x89, 0xc9,
	0xd9, 0x29, 0xf9, 0xf9, 0x45, 0xfa, 0xd5, 0x20, 0xa1, 0xda, 0x24, 0x36, 0xb0, 0xa7, 0x8c, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x98, 0xb1, 0xc5, 0xac, 0x0b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PingPongClient is the client API for PingPong service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PingPongClient interface {
	//    rpc PingPong (Ping) returns (Pong) {
	//        option (google.api.http) = {
	//            get: "/pingpong/{ping}"
	//        };
	//    }
	//
	Stream(ctx context.Context, opts ...grpc.CallOption) (PingPong_StreamClient, error)
	Backend(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error)
}

type pingPongClient struct {
	cc *grpc.ClientConn
}

func NewPingPongClient(cc *grpc.ClientConn) PingPongClient {
	return &pingPongClient{cc}
}

func (c *pingPongClient) Stream(ctx context.Context, opts ...grpc.CallOption) (PingPong_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PingPong_serviceDesc.Streams[0], "/demo.PingPong/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &pingPongStreamClient{stream}
	return x, nil
}

type PingPong_StreamClient interface {
	Send(*Ping) error
	Recv() (*Pong, error)
	grpc.ClientStream
}

type pingPongStreamClient struct {
	grpc.ClientStream
}

func (x *pingPongStreamClient) Send(m *Ping) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pingPongStreamClient) Recv() (*Pong, error) {
	m := new(Pong)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pingPongClient) Backend(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := c.cc.Invoke(ctx, "/demo.PingPong/Backend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PingPongServer is the server API for PingPong service.
type PingPongServer interface {
	//    rpc PingPong (Ping) returns (Pong) {
	//        option (google.api.http) = {
	//            get: "/pingpong/{ping}"
	//        };
	//    }
	//
	Stream(PingPong_StreamServer) error
	Backend(context.Context, *Ping) (*Pong, error)
}

// UnimplementedPingPongServer can be embedded to have forward compatible implementations.
type UnimplementedPingPongServer struct {
}

func (*UnimplementedPingPongServer) Stream(srv PingPong_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (*UnimplementedPingPongServer) Backend(ctx context.Context, req *Ping) (*Pong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Backend not implemented")
}

func RegisterPingPongServer(s *grpc.Server, srv PingPongServer) {
	s.RegisterService(&_PingPong_serviceDesc, srv)
}

func _PingPong_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PingPongServer).Stream(&pingPongStreamServer{stream})
}

type PingPong_StreamServer interface {
	Send(*Pong) error
	Recv() (*Ping, error)
	grpc.ServerStream
}

type pingPongStreamServer struct {
	grpc.ServerStream
}

func (x *pingPongStreamServer) Send(m *Pong) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pingPongStreamServer) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PingPong_Backend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingPongServer).Backend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/demo.PingPong/Backend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingPongServer).Backend(ctx, req.(*Ping))
	}
	return interceptor(ctx, in, info, handler)
}

var _PingPong_serviceDesc = grpc.ServiceDesc{
	ServiceName: "demo.PingPong",
	HandlerType: (*PingPongServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Backend",
			Handler:    _PingPong_Backend_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _PingPong_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ping-pong.proto",
}
